name: Generate and update GitHub Stats

on:
  push:
    branches:
      - master
  schedule:
    # Runs automatically every day at 00:00 UTC (7 AM Vietnam time)
    - cron: '0 0 * * *'
  # Allows you to manually trigger it from the "Actions" tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit the new SVG image back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate extended stats table
        uses: stats-organization/github-readme-stats-action@main
        with:
          card: stats
          options: username=catmans1
          path: github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg
          git commit -m "Update GitHub Stats" || exit 0
          git push
