name: Generate Snake Animation

on:
  push:
    branches:
      - master
      - main
  schedule:
    # Runs automatically every day at 00:00 UTC (7 AM Vietnam time)
    - cron: '0 0 * * *'
  # Allows you to manually trigger it from the "Actions" tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit the new SVG image back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ===== SNAKE ANIMATION =====
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: catmans1
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}